<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="AyeshAmir" failures="2" tests="5" name="chrometest" time="47.465" errors="0" timestamp="2025-08-25T00:16:20 IST">
  <testcase classname="testCases.TC003_loginDDT" name="verify_loginDDT" time="11.329">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_loginDDT.verify_loginDDT(TC003_loginDDT.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCases.TC003_loginDDT" name="verify_loginDDT" time="11.185"/>
  <testcase classname="testCases.TC003_loginDDT" name="verify_loginDDT" time="1.691"/>
  <testcase classname="testCases.TC003_loginDDT" name="verify_loginDDT" time="11.077"/>
  <testcase classname="testCases.TC003_loginDDT" name="verify_loginDDT" time="0.297">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_loginDDT.verify_loginDDT(TC003_loginDDT.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
</testsuite> <!-- chrometest -->
